# Generated by Django 4.1.6 on 2023-02-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_auto_20190101_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
